version: "3"
services:
  db:
    image: mysql:8
    container_name: "school-mysql"
    command: --sql-mode=NO_ENGINE_SUBSTITUTION
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_school
      MYSQL_USER: db_school
      MYSQL_PASSWORD: db_school
    networks:
      - school-network

networks:
  school-network:
    driver: bridge

volumes:
  db-data:
